theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "notify"

[[block]]
block = "sound"

[[block]]
block = "networkmanager"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+', 'virbr\d+']
interface_name_include = []
ap_format = "{ssid} ({strength})"

[[block]]
block = "battery"
format = "{percentage} {time}"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {available} free"
alert_absolute = true
unit = "GB"
alert = 350
warning = 400

[[block]]
block = "load"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
idle = 65
info = 75
format = "{average}"
chip = "coretemp-isa-0000"
inputs = ["Package id 0"]

[[block]]
block = "memory"
format_mem = "{mem_used} used"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

